import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar/Navbar'
import '@/public/css/bootstrap.min.css';
import '@/public/css/styles.css';
import '@/public/css/mobileResponsive.css';
import '@/public/css/tabResponsive.css'
import 'react-responsive-carousel/lib/styles/carousel.min.css';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SKW INVESTMENT',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <div className='mobile-nav' style={{ position: 'sticky', top: 0, background: '#FFFFFF', zIndex: 99}}>
          <Navbar/>
          </div>
          {children}
        </div>
      </body>
    </html>
  )
}
